language: python

python:
  - '3.7'

install:
  - pip3 install "HookTest<2.0.0"

script: hooktest ./ --scheme tei --workers 3 --verbose 5 --manifest --countword --console table --allowfailure 

before_deploy:
  - hooktest-build --travis ./
  - DATE=`date +%Y-%m-%d`
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$major_version.$minor_version.$TRAVIS_BUILD_NUMBER
  - git add -A
  - git commit -m "Removed failing files" -m "Release $GIT_TAG"
  - git tag $GIT_TAG -a -m "$DATE"
  - git push -q https://$GSEC@github.com/ponteineptique/digiliblt --tags

deploy:
  provider: releases
  api_key: $GSEC
  skip_cleanup: true
  on:
    branch: master

env:
  global:
    major_version: 0
    minor_version: 0
